name: Provisionierung S3 Storage Bucket


# Controls when the workflow will run
on:
   workflow_dispatch:
    inputs:
      s3-name:
        description: s3 storage name
        required: true
        default: ''
        type: string
      s3-visibility:
        description: s3 public or private
        required: true
        options:
        - public
        - private
      message:
        description: Ticketnumber / Change
        required: true
      environment:
        type: environment
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
